//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caretakers_Teams
    {
        public int ID { get; set; }
        public int Caretaker_ID { get; set; }
        public int Animal_Type_ID { get; set; }
    
        public virtual Animal_Types Animal_Types { get; set; }
        public virtual Caretakers Caretakers { get; set; }
    }
}
