//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enclousers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enclousers()
        {
            this.Animals = new HashSet<Animals>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Capacity { get; set; }
        public int Visiting_Hours_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animals> Animals { get; set; }
        public virtual Visiting_Hours Visiting_Hours { get; set; }
    }
}
